export { default as Skills } from './skills';
export { Projects } from './projects';
export { Experience } from './experience';
export { Education } from './education';
export { Contact } from './contact';
export { Hero } from './hero';
export { Navigation } from './navigation';
export { default as Goals } from './goals';
export { Certifications } from './certifications';
export { Testimonials } from './testimonials';